<?php

/**
 * Implements hook_install().
 */
function gsb_feature_google_tag_manager_install() {
  if (!module_exists('google_tag')) {
    module_enable(array('google_tag'));
  }
}

/**
 * Implements hook_uninstall().
 */
function gsb_feature_google_tag_manager_uninstall() {
}

function gsb_feature_google_tag_manager_update_7001() {
  if (!module_exists('google_tag')) {
    module_enable(array('google_tag'));
  }
}
