<?php
/**
* @file
* Code for the GSB Feature Google Tag Manager
*/

/**
* Implements hook_page_alter().
*
* Adds a post_render callback.
*
* @see drupal_render_page()
*/
function gsb_feature_google_tag_manager_page_alter(&$page) {
  if (!google_tag_insert_snippet()) {
    return;
  }
  // Add callback routine.
  $page['#post_render'][] = 'gsb_feature_google_tag_manager_page_process';
}

/**
* Implements callback_post_render().
*
* Inserts JavaScript snippet immediately following the opening body tag.
*
* @see google_tag_page_alter()
* @see drupal_render()
*/
function gsb_feature_google_tag_manager_page_process(&$children, $elements) {

  if (arg(0) == 'node' && is_numeric(arg(1))) {

    $node = node_load(arg(1));
    $type_name = node_type_get_name($node);

    $script = "<script> dataLayer = []; dataLayer.push({";

    for ($index = 0; $index < 3; $index++) {
      if (!empty($node->field_key_taxonomy[$node->language][$index]['target_id'])) {
        $tid = $node->field_key_taxonomy[$node->language][$index]['target_id'];
        $taxonomy = taxonomy_term_load($tid);
        $dim = $index + 1;
        $script .= " 'dimension$dim' : '$taxonomy->name', ";
      }
    }

    $script .= " 'dimension4' : '$type_name' ";
    $script .= "});</script>";

    // Insert snippet after the opening body tag.
    $children = preg_replace('@<body[^>]*>@', '$0' . $script, $children, 1);
  }

  return $children;
}
